"""
Pattern Detection System: Detects IN and OUT patterns in swing data.

The system analyzes swing points (highs/lows from EMA crosses) and classifies them
as IN or OUT based on a 0-1-2-3 pattern structure.

Modules:
  - data_loader: Load zigzag swing data from CSV
  - swing_structure_validator: Normalize and validate swing sequence
  - pattern_detector: Find valid bullish/bearish patterns
  - intersection_detector: Track pattern intersections
  - pattern_classifier: Classify swing points as IN or OUT
  - result_exporter: Save results to CSV
"""

import pandas as pd
import numpy as np
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass


@dataclass
class SwingPoint:
    """Represents a single swing point in the sequence."""
    index: int
    price: float
    type: str  # 'HIGH' or 'LOW'
    date: Optional[str] = None
    
    def __repr__(self):
        return f"SwingPoint(idx={self.index}, price={self.price}, type={self.type})"


@dataclass
class Pattern:
    """Represents a detected 0-1-2-3 pattern."""
    points: List[SwingPoint]  # [point0, point1, point2, point3]
    pattern_type: str  # 'BULLISH' or 'BEARISH'
    
    def __repr__(self):
        prices = [p.price for p in self.points]
        return f"Pattern({self.pattern_type}, prices={prices})"


class DataLoader:
    """Load swing data from CSV."""
    
    @staticmethod
    def load_zigzag_csv(csv_path: str) -> List[SwingPoint]:
        """Load swing points from the zigzag CSV generated by analyze_nepal_stock.py"""
        df = pd.read_csv(csv_path)
        
        swings = []
        for idx, row in df.iterrows():
            swing = SwingPoint(
                index=idx,
                price=row['price'],
                type=row['type'].upper(),
                date=row.get('date', None)
            )
            swings.append(swing)
        
        return swings


class SwingStructureValidator:
    """Validate and normalize swing sequence."""
    
    @staticmethod
    def normalize_swings(swings: List[SwingPoint]) -> List[SwingPoint]:
        """
        Ensure swing sequence alternates: HIGH-LOW-HIGH-LOW or LOW-HIGH-LOW-HIGH
        If consecutive same types exist, keep the extreme value (higher high, lower low).
        """
        if len(swings) < 2:
            return swings
        
        normalized = [swings[0]]
        
        for i in range(1, len(swings)):
            current = swings[i]
            last = normalized[-1]
            
            if current.type == last.type:
                # Same type: replace with the more extreme one
                if current.type == 'HIGH':
                    if current.price > last.price:
                        normalized[-1] = current
                else:  # LOW
                    if current.price < last.price:
                        normalized[-1] = current
            else:
                # Different type: add it
                normalized.append(current)
        
        return normalized
    
    @staticmethod
    def validate_alternation(swings: List[SwingPoint]) -> bool:
        """Check that sequence alternates between HIGH and LOW."""
        if len(swings) < 2:
            return True
        
        for i in range(len(swings) - 1):
            if swings[i].type == swings[i + 1].type:
                return False
        return True


class PatternDetector:
    """Detect valid 0-1-2-3 patterns."""
    
    @staticmethod
    def detect_all_patterns(swings: List[SwingPoint]) -> List[Pattern]:
        """
        Iterate through all swing points and detect valid 0-1-2-3 patterns.
        """
        patterns = []
        
        # Try each swing as a potential point 0
        for i in range(len(swings) - 3):
            point0 = swings[i]
            point1 = swings[i + 1]
            point2 = swings[i + 2]
            point3 = swings[i + 3]
            
            # Check for bullish pattern
            if PatternDetector._is_bullish_pattern(point0, point1, point2, point3):
                pattern = Pattern([point0, point1, point2, point3], 'BULLISH')
                patterns.append(pattern)
            
            # Check for bearish pattern
            elif PatternDetector._is_bearish_pattern(point0, point1, point2, point3):
                pattern = Pattern([point0, point1, point2, point3], 'BEARISH')
                patterns.append(pattern)
        
        return patterns
    
    @staticmethod
    def _is_bullish_pattern(p0: SwingPoint, p1: SwingPoint, p2: SwingPoint, p3: SwingPoint) -> bool:
        """
        Bullish pattern:
        0 = LOW
        1 = HIGH
        2 = LOW where price(2) > price(0)
        3 = HIGH where price(3) > price(1)
        """
        return (
            p0.type == 'LOW' and
            p1.type == 'HIGH' and
            p2.type == 'LOW' and
            p3.type == 'HIGH' and
            p2.price > p0.price and
            p3.price > p1.price
        )
    
    @staticmethod
    def _is_bearish_pattern(p0: SwingPoint, p1: SwingPoint, p2: SwingPoint, p3: SwingPoint) -> bool:
        """
        Bearish pattern:
        0 = HIGH
        1 = LOW
        2 = HIGH where price(2) < price(0)
        3 = LOW where price(3) < price(1)
        """
        return (
            p0.type == 'HIGH' and
            p1.type == 'LOW' and
            p2.type == 'HIGH' and
            p3.type == 'LOW' and
            p2.price < p0.price and
            p3.price < p1.price
        )


class IntersectionDetector:
    """Detect intersections between patterns."""
    
    @staticmethod
    def find_intersections(patterns: List[Pattern]) -> Dict[int, List[int]]:
        """
        Find which patterns share swing points.
        Returns: {pattern_idx: [list of other pattern indices it intersects with]}
        
        A swing point at position 3 of pattern A can be position 0 of pattern B.
        """
        intersections = {}
        
        for i in range(len(patterns)):
            intersections[i] = []
            pattern_a = patterns[i]
            
            for j in range(len(patterns)):
                if i == j:
                    continue
                
                pattern_b = patterns[j]
                
                # Check if any point of pattern_a appears in pattern_b
                for p_a in pattern_a.points:
                    for p_b in pattern_b.points:
                        if p_a.index == p_b.index:
                            if j not in intersections[i]:
                                intersections[i].append(j)
                            break
        
        return intersections


class PatternClassifier:
    """Classify swing points as IN or OUT."""
    
    @staticmethod
    def classify(swings: List[SwingPoint], patterns: List[Pattern], 
                 intersections: Dict[int, List[int]]) -> Dict[int, Tuple[str, Optional[int]]]:
        """
        Classify each swing point as IN or OUT.
        
        Returns: {swing_index: (classification, pattern_role)}
        where:
          classification = 'IN' or 'OUT'
          pattern_role = 0, 1, 2, 3, or None
        """
        classification = {}
        
        # Initialize all swings as OUT
        for swing in swings:
            classification[swing.index] = ('OUT', None)
        
        # Track which swing points appear in patterns and their roles
        swing_to_patterns = {}  # swing_index -> [(pattern_idx, role), ...]
        
        for pattern_idx, pattern in enumerate(patterns):
            for role, point in enumerate(pattern.points):
                if point.index not in swing_to_patterns:
                    swing_to_patterns[point.index] = []
                swing_to_patterns[point.index].append((pattern_idx, role))
        
        # Classify swings based on pattern membership and intersections
        for swing_idx, pattern_list in swing_to_patterns.items():
            # Check if this swing appears in multiple patterns (intersection)
            if len(pattern_list) > 1:
                # It's IN if it participates in multiple patterns
                # Use the first role for output (could be in different roles)
                _, role = pattern_list[0]
                classification[swing_idx] = ('IN', role)
            else:
                # It appears in only one pattern
                pattern_idx, role = pattern_list[0]
                
                # Check if that pattern intersects with others
                if len(intersections[pattern_idx]) > 0:
                    # Pattern intersects, so this swing is IN
                    classification[swing_idx] = ('IN', role)
                else:
                    # Pattern doesn't intersect, so this swing is OUT
                    classification[swing_idx] = ('OUT', role)
        
        return classification


class ResultExporter:
    """Export results to CSV and display."""
    
    @staticmethod
    def export_classification(swings: List[SwingPoint], 
                             classification: Dict[int, Tuple[str, Optional[int]]],
                             output_path: str) -> None:
        """Export classification results to CSV."""
        results = []
        
        for swing in swings:
            if swing.index in classification:
                cls, role = classification[swing.index]
            else:
                cls, role = 'OUT', None
            
            role_str = str(role) if role is not None else 'NONE'
            
            results.append({
                'index': swing.index,
                'price': swing.price,
                'type': swing.type,
                'date': swing.date,
                'pattern_role': role_str,
                'classification': cls
            })
        
        df = pd.DataFrame(results)
        df.to_csv(output_path, index=False)
        print(f"✓ Results exported to {output_path}")
        
        # Print summary
        in_count = (df['classification'] == 'IN').sum()
        out_count = (df['classification'] == 'OUT').sum()
        print(f"\nSummary:")
        print(f"  IN patterns: {in_count}")
        print(f"  OUT patterns: {out_count}")
        print(f"  Total swings: {len(df)}")
    
    @staticmethod
    def plot_classification(swings: List[SwingPoint], 
                           classification: Dict[int, Tuple[str, Optional[int]]],
                           symbol: str, output_path: str) -> None:
        """Visualize the IN/OUT classification with pattern role labels."""
        try:
            import matplotlib.pyplot as plt
        except ImportError:
            print("⚠ Matplotlib not available, skipping visualization")
            return
        
        # Prepare data
        dates = [s.date for s in swings]
        prices = [s.price for s in swings]
        
        fig, ax = plt.subplots(figsize=(24, 10))
        
        # Plot the zigzag line
        ax.plot(dates, prices, label='Swing Zigzag', color='navy', linewidth=2.5, marker='o', markersize=6, alpha=0.6)
        
        # Plot points with their classification
        for swing in swings:
            if swing.index in classification:
                cls, role = classification[swing.index]
            else:
                cls, role = 'OUT', None
            
            if cls == 'OUT':
                # OUT points: red dot, no label
                ax.scatter(swing.date, swing.price, color='red', s=200, zorder=5, alpha=0.7)
            else:
                # IN points: label with pattern role (0, 1, 2, 3)
                if role is not None:
                    color = 'green'
                    ax.scatter(swing.date, swing.price, color=color, s=250, zorder=5, alpha=0.85, edgecolors='black', linewidth=1.5)
                    ax.text(swing.date, swing.price, str(role), fontsize=10, fontweight='bold', 
                           ha='center', va='center', color='black')
        
        ax.set_xlabel('Date', fontsize=14)
        ax.set_ylabel('Price', fontsize=14)
        ax.set_title(f'{symbol} - IN/OUT Pattern Classification (0-1-2-3 Labels)', fontsize=16, fontweight='bold')
        ax.grid(True, alpha=0.3)
        
        # Custom legend
        from matplotlib.patches import Patch
        legend_elements = [
            Patch(facecolor='green', edgecolor='black', label='IN Pattern (labeled 0-1-2-3)'),
            Patch(facecolor='red', label='OUT Pattern (invalid or non-intersecting)')
        ]
        ax.legend(handles=legend_elements, loc='best', fontsize=12)
        
        fig.autofmt_xdate(rotation=45, ha='right')
        plt.tight_layout()
        
        fig.savefig(output_path, dpi=300, bbox_inches='tight')
        print(f"✓ Classification chart saved: {output_path}")
    
    @staticmethod
    def print_patterns(patterns: List[Pattern]) -> None:
        """Print detected patterns."""
        print(f"\nDetected {len(patterns)} valid patterns:")
        for i, pattern in enumerate(patterns):
            prices = [p.price for p in pattern.points]
            print(f"  Pattern {i}: {pattern.pattern_type} {prices}")


def analyze_pattern(symbol: str, zigzag_csv: str, output_csv: str):
    """
    Main entry point: run the full pattern detection pipeline.
    """
    print(f"\n{'='*60}")
    print(f"Pattern Detection: {symbol}")
    print(f"{'='*60}\n")
    
    # 1. Load swing data
    print("1. Loading swing data...")
    swings = DataLoader.load_zigzag_csv(zigzag_csv)
    print(f"   Loaded {len(swings)} swing points")
    
    # 2. Normalize swing sequence
    print("2. Normalizing swing sequence...")
    swings = SwingStructureValidator.normalize_swings(swings)
    print(f"   Normalized to {len(swings)} swing points")
    
    if not SwingStructureValidator.validate_alternation(swings):
        print("   ⚠ Warning: Sequence does not properly alternate")
    
    # 3. Detect patterns
    print("3. Detecting 0-1-2-3 patterns...")
    patterns = PatternDetector.detect_all_patterns(swings)
    print(f"   Detected {len(patterns)} valid patterns")
    
    if len(patterns) > 0:
        ResultExporter.print_patterns(patterns[:5])  # Print first 5
    
    # 4. Detect intersections
    print("4. Detecting pattern intersections...")
    intersections = IntersectionDetector.find_intersections(patterns)
    intersecting_count = sum(1 for v in intersections.values() if len(v) > 0)
    print(f"   {intersecting_count} patterns intersect with others")
    
    # 5. Classify swings
    print("5. Classifying swing points as IN or OUT...")
    classification = PatternClassifier.classify(swings, patterns, intersections)
    
    # 6. Export results
    print("6. Exporting results...")
    import os
    os.makedirs(os.path.dirname(output_csv), exist_ok=True)
    ResultExporter.export_classification(swings, classification, output_csv)
    
    # 7. Visualize classification
    print("7. Generating classification visualization...")
    viz_path = output_csv.replace("/csv/", "/png/").replace(".csv", "_visualization.png")
    os.makedirs(os.path.dirname(viz_path), exist_ok=True)
    ResultExporter.plot_classification(swings, classification, symbol, viz_path)
    
    print(f"\n✓ Pattern detection complete!\n")


if __name__ == '__main__':
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python pattern_detector.py <symbol> [--zigzag-csv path] [--output-csv path]")
        sys.exit(1)
    
    symbol = sys.argv[1]
    
    # Default paths
    zigzag_csv = f'stocks/nepal/{symbol}/results/csv/highs_lows_pattern_9_18.csv'
    output_csv = f'stocks/nepal/{symbol}/results/csv/in_out_pattern_9_18.csv'
    
    # Override if provided
    if '--zigzag-csv' in sys.argv:
        idx = sys.argv.index('--zigzag-csv')
        zigzag_csv = sys.argv[idx + 1]
    if '--output-csv' in sys.argv:
        idx = sys.argv.index('--output-csv')
        output_csv = sys.argv[idx + 1]
    
    analyze_pattern(symbol, zigzag_csv, output_csv)
