"""
Trend-Based Pattern Detection System: Detects IN and OUT patterns based on valid trend continuation.

The system analyzes swing points and marks them as part of valid trends:
- 0: Start of a valid trend (higher low + higher high for uptrend, or lower high + lower low for downtrend)
- 1, 2, 3, ...: Continuation of the trend
- OUT: Isolated points or trend breaks

IN Pattern: Points marked as 1, 2, 3... (part of continuous trends)
OUT Pattern: Points not in a trend, or 0 points without valid continuation
"""

import pandas as pd
import numpy as np
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass


@dataclass
class SwingPoint:
    """Represents a single swing point in the sequence."""
    index: int
    price: float
    type: str  # 'HIGH' or 'LOW'
    date: Optional[str] = None
    
    def __repr__(self):
        return f"SwingPoint(idx={self.index}, price={self.price}, type={self.type})"


class DataLoader:
    """Load swing data from CSV."""
    
    @staticmethod
    def load_zigzag_csv(csv_path: str) -> List[SwingPoint]:
        """Load swing points from the zigzag CSV generated by analyze_nepal_stock.py"""
        df = pd.read_csv(csv_path)
        
        swings = []
        for idx, row in df.iterrows():
            swing = SwingPoint(
                index=idx,
                price=row['price'],
                type=row['type'].upper(),
                date=row.get('date', None)
            )
            swings.append(swing)
        
        return swings


class TrendValidator:
    """Validate and identify valid trends."""
    
    @staticmethod
    def is_valid_complete_uptrend(p0: SwingPoint, p1: SwingPoint, p2: SwingPoint, p3: SwingPoint) -> bool:
        """
        Validate a COMPLETE UPTREND (0→1→2→3) with exact sequence:
        0=LOW, 1=HIGH, 2=LOW, 3=HIGH
        
        Structure Requirements:
        - HL (Higher Low): p2.LOW > p0.LOW (point 2 is higher low than point 0)
        - HH (Higher High): p3.HIGH > p1.HIGH (point 3 is higher high than point 1)
        
        This ensures the pattern forms: HL → HH (valid uptrend)
        """
        return (
            # Type sequence check
            p0.type == 'LOW' and
            p1.type == 'HIGH' and
            p2.type == 'LOW' and
            p3.type == 'HIGH' and
            # Price structure check
            p2.price > p0.price and  # HL: Higher Low
            p3.price > p1.price      # HH: Higher High
        )
    
    @staticmethod
    def is_valid_complete_downtrend(p0: SwingPoint, p1: SwingPoint, p2: SwingPoint, p3: SwingPoint) -> bool:
        """
        Validate a COMPLETE DOWNTREND (0→1→2→3) with exact sequence:
        0=HIGH, 1=LOW, 2=HIGH, 3=LOW
        
        Structure Requirements:
        - LH (Lower High): p2.HIGH < p0.HIGH (point 2 is lower high than point 0)
        - LL (Lower Low): p3.LOW < p1.LOW (point 3 is lower low than point 1)
        
        This ensures the pattern forms: LH → LL (valid downtrend)
        """
        return (
            # Type sequence check
            p0.type == 'HIGH' and
            p1.type == 'LOW' and
            p2.type == 'HIGH' and
            p3.type == 'LOW' and
            # Price structure check
            p2.price < p0.price and  # LH: Lower High
            p3.price < p1.price      # LL: Lower Low
        )
    
    @staticmethod
    def continues_uptrend(prev_swing: SwingPoint, curr_swing: SwingPoint, 
                         prev_prev: SwingPoint = None) -> bool:
        """Check if current swing continues an uptrend."""
        # In uptrend: LOW -> HIGH -> LOW(higher) -> HIGH(higher)...
        # So HIGH should be higher than previous HIGH, LOW should be higher than previous LOW
        if prev_swing.type == 'HIGH' and curr_swing.type == 'LOW':
            # LOW point: should be higher than previous LOW
            if prev_prev and prev_prev.type == 'LOW':
                return curr_swing.price > prev_prev.price
            return True  # First low in trend
        
        elif prev_swing.type == 'LOW' and curr_swing.type == 'HIGH':
            # HIGH point: should be higher than previous HIGH
            if prev_prev and prev_prev.type == 'HIGH':
                return curr_swing.price > prev_prev.price
            return True  # First high in trend
        
        return False
    
    @staticmethod
    def continues_downtrend(prev_swing: SwingPoint, curr_swing: SwingPoint,
                           prev_prev: SwingPoint = None) -> bool:
        """Check if current swing continues a downtrend."""
        # In downtrend: HIGH -> LOW -> HIGH(lower) -> LOW(lower)...
        # So HIGH should be lower than previous HIGH, LOW should be lower than previous LOW
        if prev_swing.type == 'LOW' and curr_swing.type == 'HIGH':
            # HIGH point: should be lower than previous HIGH
            if prev_prev and prev_prev.type == 'HIGH':
                return curr_swing.price < prev_prev.price
            return True  # First high in trend
        
        elif prev_swing.type == 'HIGH' and curr_swing.type == 'LOW':
            # LOW point: should be lower than previous LOW
            if prev_prev and prev_prev.type == 'LOW':
                return curr_swing.price < prev_prev.price
            return True  # First low in trend
        
        return False


class TrendDetector:
    """Detect and mark valid trends in swing sequence."""
    
    @staticmethod
    def detect_trends(swings: List[SwingPoint]) -> Tuple[Dict[int, Tuple[str, int]], List[Tuple[int, List[int], str]]]:
        """
        Detect valid trends as strict 4-point windows only:
        each valid pattern is exactly 0-1-2-3.
        Scan every next point as a potential new start (0), so windows can overlap.
        
        UPTREND (0→1→2→3): LOW → HIGH → LOW → HIGH
                 Structure: HL (Higher Low) + HH (Higher High)
                 p2.LOW > p0.LOW AND p3.HIGH > p1.HIGH
        
        DOWNTREND (0→1→2→3): HIGH → LOW → HIGH → LOW
                   Structure: LH (Lower High) + LL (Lower Low)
                   p2.HIGH < p0.HIGH AND p3.LOW < p1.LOW
        
        Any other combination is INVALID and marked as OUT.
        Returns classified swings and sequence list.
        """
        classification: Dict[int, Tuple[str, int]] = {}
        all_sequences_list: List[Tuple[int, List[int], str]] = []

        for i in range(len(swings) - 3):
            p0 = swings[i]
            p1 = swings[i + 1]
            p2 = swings[i + 2]
            p3 = swings[i + 3]

            trend_type = None
            if TrendValidator.is_valid_complete_uptrend(p0, p1, p2, p3):
                trend_type = 'UPTREND'
            elif TrendValidator.is_valid_complete_downtrend(p0, p1, p2, p3):
                trend_type = 'DOWNTREND'

            if trend_type is None:
                continue

            seq_indices = [p0.index, p1.index, p2.index, p3.index]
            all_sequences_list.append((p0.index, seq_indices, trend_type))

        # Filter strictly for non-overlapping sequences (sharing endpoint 3 -> 0 is permitted)
        sequences_list: List[Tuple[int, List[int], str]] = []
        last_end_idx = -1
        for seq in all_sequences_list:
            if seq[1][0] >= last_end_idx:
                sequences_list.append(seq)
                last_end_idx = seq[1][3]

        membership: Dict[int, List[Tuple[str, int]]] = {}
        for seq in sequences_list:
            for role, swing_index in enumerate(seq[1]):
                membership.setdefault(swing_index, []).append((seq[2], role))

        # Decide final trend/role per swing (for basic tuple return):
        # We also prioritize role 0 here so the exporter prints it correctly.
        for swing in swings:
            entries = membership.get(swing.index, [])
            if not entries:
                classification[swing.index] = ('NONE', -1)
                continue

            zero_entries = [e for e in entries if e[1] == 0]
            nonzero_entries = [e for e in entries if e[1] > 0]
            
            if zero_entries:
                trend_type, role = zero_entries[-1]
                classification[swing.index] = (trend_type, role)
            elif nonzero_entries:
                trend_type, role = nonzero_entries[0]
                classification[swing.index] = (trend_type, role)
        
        return classification, sequences_list


class PatternClassifier:
    """Classify swings as IN or OUT."""
    
    @staticmethod
    def classify(swings: List[SwingPoint], 
                 trends: Dict[int, Tuple[str, int]],
                 sequences_list: List[Tuple[int, List[int], str]]) -> Dict[int, Tuple[str, Optional[int], str, str]]:
        """
        Classify each swing into directional IN/OUT labels.
        
        point_label values:
          - IN_UP / IN_DOWN: role 1,2,3 in an up/down valid trend
          - OUT_UP / OUT_DOWN: role 0 of an up/down valid trend
          - unlabeled: not part of any valid 0-1-2-3 trend
        """
        classification: Dict[int, Tuple[str, Optional[int], str, str]] = {}

        # Build role map per pattern and detect whether each pattern start (role 0) is IN or OUT.
        # Rule: start (0) is IN if it is also 1/2/3 of any other valid pattern.
        start_in: Dict[int, bool] = {}
        start_trend: Dict[int, str] = {}
        pattern_roles: List[Dict[int, int]] = []
        pattern_trends: List[str] = []
        for seq_idx, seq_indices, trend_type in sequences_list:
            role_map = {idx: role for role, idx in enumerate(seq_indices)}
            pattern_roles.append(role_map)
            pattern_trends.append(trend_type)
            start_trend[seq_indices[0]] = trend_type

        # Index swing membership in patterns
        swing_to_patterns: Dict[int, List[Tuple[int, int]]] = {}
        for p_idx, role_map in enumerate(pattern_roles):
            for idx, role in role_map.items():
                swing_to_patterns.setdefault(idx, []).append((p_idx, role))

        # Determine whether each pattern start is IN (overlaps another pattern's 1/2/3)
        for p_idx, role_map in enumerate(pattern_roles):
            start_idx = [k for k, v in role_map.items() if v == 0]
            if not start_idx:
                continue
            s_idx = start_idx[0]
            overlaps = swing_to_patterns.get(s_idx, [])
            start_in[p_idx] = any(role in (1, 2, 3) and other_idx != p_idx for other_idx, role in overlaps)

        # Assign labels based on pattern start rule:
        # - role 0 is OUT unless it overlaps another pattern's 1/2/3
        # - roles 1/2/3 are always IN (trend direction)
        for swing in swings:
            memberships = swing_to_patterns.get(swing.index, [])
            if not memberships:
                continue

            # Find if this swing acts as role 0 in ANY pattern
            role_0_patterns = [p for p, role in memberships if role == 0]
            
            if role_0_patterns:
                # Prioritize the pattern where it is role 0.
                # If there are multiple, just pick the first one.
                chosen_p = role_0_patterns[-1]
                role = 0
            else:
                # If not role 0 anywhere, prioritize IN patterns
                in_patterns = [p for p, _ in memberships if start_in.get(p, False)]
                chosen_p = in_patterns[0] if in_patterns else memberships[0][0]
                role = dict(memberships).get(chosen_p, memberships[0][1])

            trend_type = pattern_trends[chosen_p]

            if role == 0 and not start_in.get(chosen_p, False):
                if trend_type == 'UPTREND':
                    classification[swing.index] = ('OUT', role, trend_type, 'OUT_UP')
                else:
                    classification[swing.index] = ('OUT', role, trend_type, 'OUT_DOWN')
            else:
                if trend_type == 'UPTREND':
                    classification[swing.index] = ('IN', role, trend_type, 'IN_UP')
                else:
                    classification[swing.index] = ('IN', role, trend_type, 'IN_DOWN')

        return classification


class ResultExporter:
    """Export results to CSV and display."""
    
    @staticmethod
    def export_classification(swings: List[SwingPoint], 
                             classification: Dict[int, Tuple[str, Optional[int], str, str]],
                             output_path: str) -> None:
        """Export classification results to CSV."""
        results = []
        
        for swing in swings:
            if swing.index in classification:
                cls, role, trend_type, point_label = classification[swing.index]
            else:
                cls, role, trend_type, point_label = '', None, '', ''
            
            role_str = str(role) if role is not None and role >= 0 else ''
            
            results.append({
                'index': swing.index,
                'price': swing.price,
                'type': swing.type,
                'date': swing.date,
                'pattern_role': role_str,
                'classification': cls,
                'trend_type': trend_type,
                'point_label': point_label
            })
        
        df = pd.DataFrame(results)
        df.to_csv(output_path, index=False)
        print(f"✓ Results exported to {output_path}")
        
        # Print summary
        in_count = (df['classification'] == 'IN').sum()
        out_count = (df['classification'] == 'OUT').sum()
        unlabeled_count = (df['classification'] == '').sum()
        in_up_count = (df['point_label'] == 'IN_UP').sum()
        in_down_count = (df['point_label'] == 'IN_DOWN').sum()
        out_up_count = (df['point_label'] == 'OUT_UP').sum()
        out_down_count = (df['point_label'] == 'OUT_DOWN').sum()
        print(f"\nSummary:")
        print(f"  IN points: {in_count}")
        print(f"  OUT points: {out_count}")
        print(f"  Unlabeled points: {unlabeled_count}")
        print(f"  IN_UP: {in_up_count}")
        print(f"  IN_DOWN: {in_down_count}")
        print(f"  OUT_UP: {out_up_count}")
        print(f"  OUT_DOWN: {out_down_count}")
        print(f"  Total swings: {len(df)}")
    
    @staticmethod
    def plot_classification(swings: List[SwingPoint], 
                           classification: Dict[int, Tuple[str, Optional[int], str, str]],
                           symbol: str, output_path: str) -> None:
        """Visualize the IN/OUT classification with pattern role labels."""
        try:
            import matplotlib.pyplot as plt
            import matplotlib.dates as mdates
            import pandas as pd
        except ImportError:
            print("⚠ Matplotlib not available, skipping visualization")
            return
        
        # Prepare data
        dates = [pd.to_datetime(s.date) for s in swings]
        date_by_index = {s.index: pd.to_datetime(s.date) for s in swings}
        prices = [s.price for s in swings]

        # Adaptive canvas: keep readable but avoid excessive rendering cost.
        date_span_days = max(1, int((max(dates) - min(dates)).days)) if dates else 1
        width = min(54, max(26, date_span_days / 45.0))
        fig, ax = plt.subplots(figsize=(width, 10))
        
        # Plot the zigzag line
        ax.plot(dates, prices, label='Swing Zigzag', color='navy', linewidth=2.5, marker='o', markersize=6, alpha=0.6)
        
        # Plot points with their classification
        for swing in swings:
            x_date = date_by_index.get(swing.index, pd.to_datetime(swing.date))
            if swing.index in classification:
                cls, role, trend_type, point_label = classification[swing.index]
            else:
                cls, role, trend_type, point_label = '', None, '', ''
            
            if cls == 'OUT':
                # OUT points: red dot, no label
                ax.scatter(x_date, swing.price, color='red', s=200, zorder=5, alpha=0.7)
            elif cls == '':
                # Unlabeled/invalid points: lighter red to distinguish from true OUT(0) points.
                ax.scatter(
                    x_date,
                    swing.price,
                    color='lightcoral',
                    s=120,
                    marker='x',
                    zorder=4,
                    alpha=0.65,
                )
            else:
                # IN points: label with role 0/1/2/3 and trend direction color
                if role is not None and role >= 0:
                    color = 'green' if point_label == 'IN_UP' else 'dodgerblue'
                    ax.scatter(x_date, swing.price, color=color, s=300, zorder=6, alpha=0.9, edgecolors='black', linewidth=2)
                    # Add text label above the point
                    ax.text(x_date, swing.price + (max(prices) - min(prices)) * 0.02, str(role), 
                           fontsize=12, fontweight='bold', ha='center', va='bottom', 
                           color='darkgreen', bbox=dict(boxstyle='round,pad=0.3', facecolor='yellow', alpha=0.7))
            
            # Common Date label at crossover point for ALL points
            ax.text(
                x_date,
                swing.price - (max(prices) - min(prices)) * 0.02,
                x_date.strftime('%d %b'),
                fontsize=8,
                ha='center',
                va='top',
                color='black',
                alpha=0.8,
            )
        
        ax.set_xlabel('Date', fontsize=14)
        ax.set_ylabel('Price', fontsize=14)
        ax.set_title(f'{symbol} - Trend-Based IN/OUT Classification', fontsize=16, fontweight='bold')
        ax.grid(True, alpha=0.3)
        
        # Custom legend
        from matplotlib.patches import Patch
        legend_elements = [
            Patch(facecolor='green', edgecolor='black', label='IN_UP (role 1/2/3 in uptrend)'),
            Patch(facecolor='dodgerblue', edgecolor='black', label='IN_DOWN (role 1/2/3 in downtrend)'),
            Patch(facecolor='red', label='OUT_UP / OUT_DOWN'),
            Patch(facecolor='lightcoral', label='Unlabeled / Invalid')
        ]
        ax.legend(handles=legend_elements, loc='best', fontsize=12)
        
        # Adaptive date ticks (auto picks days/weeks/months based on span).
        locator = mdates.AutoDateLocator(minticks=6, maxticks=10)
        formatter = mdates.ConciseDateFormatter(locator)
        ax.xaxis.set_major_locator(locator)
        ax.xaxis.set_major_formatter(formatter)
        for lbl in ax.get_xticklabels():
            lbl.set_rotation(35)
            lbl.set_horizontalalignment('right')
            lbl.set_fontsize(9)
        plt.subplots_adjust(bottom=0.18)
        plt.tight_layout(rect=[0, 0.03, 1, 1])
        
        fig.savefig(output_path, dpi=260, bbox_inches='tight')
        print(f"✓ Classification chart saved: {output_path}")


def analyze_trend_pattern(symbol: str, zigzag_csv: str, output_csv: str):
    """
    Main entry point: run the trend-based pattern detection pipeline.
    """
    print(f"\n{'='*60}")
    print(f"Trend-Based Pattern Detection: {symbol}")
    print(f"{'='*60}\n")
    
    # 1. Load swing data
    print("1. Loading swing data...")
    swings = DataLoader.load_zigzag_csv(zigzag_csv)
    print(f"   Loaded {len(swings)} swing points")
    
    # 2. Detect trends
    print("2. Detecting valid trends (HH/HL for uptrend, LL/LH for downtrend)...")
    trends, sequences_list = TrendDetector.detect_trends(swings)
    
    trend_count = sum(1 for v in trends.values() if v[1] >= 0)
    uptrend_count = sum(1 for v in trends.values() if v[0] == 'UPTREND')
    downtrend_count = sum(1 for v in trends.values() if v[0] == 'DOWNTREND')
    print(f"   Found {trend_count} points in valid trends")
    print(f"     - Uptrend: {uptrend_count} points")
    print(f"     - Downtrend: {downtrend_count} points")
    
    # 3. Classify swings
    print("3. Classifying swing points as IN or OUT...")
    classification = PatternClassifier.classify(swings, trends, sequences_list)
    
    # 4. Export results
    print("4. Exporting results...")
    import os
    os.makedirs(os.path.dirname(output_csv), exist_ok=True)
    ResultExporter.export_classification(swings, classification, output_csv)
    
    # 5. Visualize classification
    print("5. Generating classification visualization...")
    viz_path = output_csv.replace("/csv/", "/png/").replace(".csv", "_visualization.png")
    os.makedirs(os.path.dirname(viz_path), exist_ok=True)
    ResultExporter.plot_classification(swings, classification, symbol, viz_path)
    
    print(f"\n✓ Trend-based pattern detection complete!\n")


if __name__ == '__main__':
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python pattern_detector_v2.py <symbol> [--zigzag-csv path] [--output-csv path]")
        sys.exit(1)
    
    symbol = sys.argv[1]
    
    # Default paths
    zigzag_csv = f'results/nepal/{symbol}/in_out/csv/highs_lows_pattern_9_18.csv'
    output_csv = f'results/nepal/{symbol}/in_out/csv/in_out_pattern_9_18.csv'
    
    # Override if provided
    if '--zigzag-csv' in sys.argv:
        idx = sys.argv.index('--zigzag-csv')
        zigzag_csv = sys.argv[idx + 1]
    if '--output-csv' in sys.argv:
        idx = sys.argv.index('--output-csv')
        output_csv = sys.argv[idx + 1]
    
    analyze_trend_pattern(symbol, zigzag_csv, output_csv)
